import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";
import { Header, Sidebar } from "~/_components/layout";

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mently",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chivo.className} antialiased w-full h-screen flex items-start`}
      >
        <Sidebar />
        <div className="w-full flex-1 self-start flex flex-col items-start">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
