import type { Metadata } from "next";
import { Chivo, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";

export const chivo = Chivo({ subsets: ["latin"] });
export const inter = Inter({ subsets: ["latin"] });
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chivo.className}  `}>
        <div className="grid grid-cols-[120_1fr]">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
