import type { Metadata } from "next";
import { Chivo, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Header from "./_components/Header";

export const chivo = Chivo({ subsets: ["latin"] });
export const inter = Inter({ subsets: ["latin"] });
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chivo.className}`}>
        <Sidebar />
        <div className=" ml-[120px]">
          <Header />
          <main className=" w-full mt-[70px]  ">{children}</main>
        </div>
      </body>
    </html>
  );
}
