import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/sidebar/Navbar'
import { AppProvider } from './context/AppContent'
import Sidebar from './components/sidebar/Sidebar'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className='min-h-screen flex overflow-hidden'>
            {/* SIDEBAR */}
            <Sidebar />

            {/* MAIN CONTENT SECTION */}
            <div className=' min-h-screen w-screen '>

              {/* HEADER */}
              <header className='h-[82px] w-full flex gap-2 justify-between items-center p-4 shadow-md relative z-10 bg-[#FDFDFD]'>
                <Header />
              </header>

              {/* CONTENT */}
              <main className='min-h-screen h-sreen'>
                {children}
              </main>

            </div>
          </div>
        </body>
      </html>
    </AppProvider>
  )
}
