import { Chivo } from 'next/font/google';
import "./globals.css";

// Configure Chivo font
const chivo = Chivo({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-chivo',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${chivo.variable}`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
