import { Chivo, Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${chivo.variable} ${inter.variable} flex min-h-screen bg-white antialiased`}
      >
        <div className="hidden laptop:flex">
          <Sidebar />
        </div>
        <main className="flex flex-col flex-1 laptop:ml-[120px]">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
